#!/bin/bash

if (( $# < 1 )); then
	echo "too less variables, please input 'up' or 'down'"
elif (( $# == 1)); then
	if [ $1 == "up" ]; then	
	/opt/DassaultSystemes/SIMULIA/License/lmgrd -c \
		/opt/DassaultSystemes/SIMULIA/License/ABAQUSLM_SSQ.lic
	elif [ $1 == "down" ]; then
	/opt/DassaultSystemes/SIMULIA/License/lmdown -c \
		/opt/DassaultSystemes/SIMULIA/License/ABAQUSLM_SSQ.lic
	else
		echo "invalid variable, please 'input' up or 'down'"
	fi
elif (( $# > 1)); then
	echo "too much variables, please input 'up' or 'down'"
fi
