#!/bin/bash

echo "This program is to add/remove tracker."
echo "Now, the imformation is the following."

auth=uname:password
transmission-remote -n $auth -l

if (( $# < 1 )); then
	echo "too less variables"
	echo "usage:"
	echo "2 variables:"
	echo "	app add [torrent-path|mannet(url)]"
	echo "	app remove torrent-id(only remove torrent)"
	echo "	app del torrent-id(remove torrent and delete data)"
	echo "	app start torrent-id"
	echo "	app stop torrent-id"
	echo "3 variables:"
#	echo "	app add torrent-id tracker(add-single)"
#	echo "	app remove torrent-id tracker-id(remove)"
	echo "	app curl http-webpage(add-multi)"
	echo "	app cat tracker-file(add-multi)"
elif (( $# == 2)); then
	if [ $1 == "add" ]; then	
		transmission-remote -n $auth --add $2
	elif [ $1 == "remove" ]; then
		transmission-remote -n $auth -t $2 -r
	elif [ $1 == "del" ]; then
		transmission-remote -n $auth -t $2 -rad
	elif [ $1 == "start" ]; then
		transmission-remote -n $auth -t $2 -s
	elif [ $1 == "stop" ]; then
		transmission-remote -n $auth -t $2 -S
	else
		echo "invalid variable."
	fi
elif (( $# == 3)); then
#	if [ $1 == "add" ]; then	
#		transmission-remote -n $auth -t $2 -td $3
#	elif [ $1 == "remove" ]; then
#		transmission-remote -n $auth -t $2 -tr $3
	if [ $1 == "curl" ]; then
		for tracker in `curl $3 2>&1 | grep udp`
		do
			transmission-remote -n $auth -t $2 -td $tracker
		done
	elif [ $1 == "cat" ]; then
		for tracker in `cat $3 | grep udp`
		do
			transmission-remote -n $auth -t $2 -td $tracker
		done
	else
		echo "invalid variable"
	fi
else
	echo "variables invaild, please input 'add(remove)' 'torrent id' and 'tracker(tracker id)'"
fi
